//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoTricks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texte1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texte1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemoTricks.Texte1", typeof(Texte1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Un sistem mnemonic este un sistem care face memorarea usoara, rapida si distractiva. 
        ///   Oamenilor le e greu sa isi aminteasca liste aleatorii de cuvinte, sau lucruri abstracte cum ar fi numerele sau cartile de joc, dar sunt excelenti cand vine vorba de imagini sau informatii spatiale. 
        ///   Tehnicile de memorare profita de acest lucru.
        ///
        ///                                                                                                                              .
        /// </summary>
        internal static string home_info {
            get {
                return ResourceManager.GetString("home_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot ce ai nevoie este putina imaginatie..
        /// </summary>
        internal static string home_info_2 {
            get {
                return ResourceManager.GetString("home_info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memoreaza aceasta lista de obiecte folosind sistemul Peg.                    .
        /// </summary>
        internal static string text_info_1 {
            get {
                return ResourceManager.GetString("text_info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bifeaza butonul &quot;Imagine&quot; in cazul in care nu iti amintesti imaginea corespunzatoare numarului..
        /// </summary>
        internal static string text_info_2 {
            get {
                return ResourceManager.GetString("text_info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Pentru acest exercitiu, va trebui sa memorati ordinea a 20 de jucarii. Chiar daca pare intimidant, veti observa ca metoda Loci face aceasta posibil.  
        ///   Pentru a va ajuta, am pregatit o “harta” in acest caz imaginea unei case. Apasati butonul de mai jos pentru a o vizualiza inainte de a incepe exercitiul..
        /// </summary>
        internal static string text_testLociInfo {
            get {
                return ResourceManager.GetString("text_testLociInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Pentru exercitiul urmator v-a trebui sa memorati o lista de zece obiecte ordonate aleator folosind metoda Peg apoi sa le redati in exact aceeasi ordine.
        ///   Scopul este sa aprofundati sceasta tehnica, iar pe parcurs veti observa ca timpul se va imbunatati considerabil..
        /// </summary>
        internal static string text_testPegInfo {
            get {
                return ResourceManager.GetString("text_testPegInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avion
        ///cal
        ///castel
        ///catel
        ///dinozaur
        ///masina
        ///minge
        ///papusa
        ///pistol
        ///puzzle
        ///rata
        ///robot
        ///skateboard
        ///telefon
        ///tren
        ///trompeta
        ///urs
        ///vapor
        ///xilofon
        ///yoyo
        ///zmeu.
        /// </summary>
        internal static string text_words_TestLoci {
            get {
                return ResourceManager.GetString("text_words_TestLoci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to casa
        ///masina
        ///aspirator
        ///laptop
        ///cutit
        ///sticla
        ///lant
        ///paine
        ///umbrela
        ///creion
        ///carte
        ///palarie
        ///copac
        ///papuc
        ///tun
        ///pistol
        ///minge
        ///ochelari
        ///tren
        ///scrisoare
        ///zid
        ///radio
        ///pahar.
        /// </summary>
        internal static string text_words_TestPeg {
            get {
                return ResourceManager.GetString("text_words_TestPeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Un sistem peg este o tehnica folositoare pentru memorarea unei liste de obiecte, nu foarte mare.
        ///    Un “peg” (cuier) este un carlig mintal in care agatam informatia de care avem nevoie.                      Aceasta este o tehnica usoara si foarte utila..
        /// </summary>
        internal static string text1_1 {
            get {
                return ResourceManager.GetString("text1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functioneaza prin asocierea obiectelor din lista pe care vrem sa o memoram, cu obiectele dintr-o alta lista bine cunoscuta.
        ///  O asemenea lista ar fi numerele de la 1 la 10, literele de la A la Z deoarece nu pot fi uitate. Problema cu aceste liste este ca sunt abstracte (greu de visualizat), deaceea vom asocia fiecarui numar o imagine semnificativa..
        /// </summary>
        internal static string text1_2 {
            get {
                return ResourceManager.GetString("text1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Aceasta este o lista cu imaginile pe care le-am asociat noi fiecarui numar.
        ///  Din pacate aceasta lista trebuie invatata pe de rost, totusi forma imaginilor va face acest lucru foarte simplu.  
        ///  De retinut ! (Aceste imagini nu se vor modifica, ci numai informatiile atasate lor).
        ///  Totusi, daca doriti o alta imagine mai semnificativa, aveti libertatea de a schimba, dar de la bun inceput..
        /// </summary>
        internal static string text1_3 {
            get {
                return ResourceManager.GetString("text1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemplu:
        ///   Daca al treilea element intr-o lista este o scrisoare, vom proceda in felul urmator :
        ///   -	Mai intai trebuie sa cunoastem imaginea asociata numarului 3, in cazul acesta un arc.
        ///   -	Apoi creem o imagine compusa din cele doua elemente.
        ///   Imaginea poate fi ceva interesant amuzant sau ciudat pentru ca este mai usor de reapelat..
        /// </summary>
        internal static string text1_4 {
            get {
                return ResourceManager.GetString("text1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Chiar daca nu este o tehnica prea complicata, necesita exercitiu, de aceea am creat urmatorul exercitiu  care consta in memorarea a zece obiecte dintr-o lista aleatoare..
        /// </summary>
        internal static string text1_5 {
            get {
                return ResourceManager.GetString("text1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Metoda loci ( in latina “locuri” ), de asemenea numita palatul memoriei , este o tehnica existenta inca din Roma antica folosita de oratori renumiti precum Cicero si Quintilianus , fiind cunoscuta si sub numele de “Camera romana”.
        ///    Asemenea metodei Peg, foloseste vizualizarea pentru a organiza si reaminti informatii. In acest caz, in loc de a folosi o lista memorata foloseste unele obiecte situate in locuri specifice, binecunoscute de utilizator pentru a aseza informatia..
        /// </summary>
        internal static string text2_1 {
            get {
                return ResourceManager.GetString("text2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     In cazul camerei romane, vom folosi imaginea unei camere in care va trebui mai intai sa stabilim ordinea exacta a pozitiilor in care vom aseza obiectele. Apoi vom pozitiona fiecare obiect din lista care trebuie memorata in locul corespunzator.
        ///    Cand avem nevoie sa ne reamintim obiectele, nu trebuie decat sa parcurgem camera, vizualizand obiectele asezate acolo anterior..
        /// </summary>
        internal static string text2_2 {
            get {
                return ResourceManager.GetString("text2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   De exemplu, daca avem obiectele : inghetata, ursulet de plus si zmeu, vom organiza imaginea astfel…
        ///    Cel mai mare beneficiu este ca folosind aceasta tehnica nu ai limita cand vine vorba de numarul de obiecte memorate, deoarece harta nu trebuie sa fie limitata doar la o camera.  Mai are denumirea si de “metoda calatoriei” deoarece folosind aceleasi principii, poti folosi o ruta binecunoscuta pe post de  harta mintala..
        /// </summary>
        internal static string text2_3 {
            get {
                return ResourceManager.GetString("text2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Pentru a exersa aceasta tehnica am pregatit un exercitiu  pe care il numim Provocarea Jucariilor..
        /// </summary>
        internal static string text2_4 {
            get {
                return ResourceManager.GetString("text2_4", resourceCulture);
            }
        }
    }
}
