//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoTricks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texte1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texte1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemoTricks.Texte1", typeof(Texte1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to casa
        ///masina
        ///aspirator
        ///laptop
        ///cutit
        ///sticla
        ///lant
        ///paine
        ///umbrela
        ///creion
        ///carte
        ///palarie
        ///copac
        ///papuc
        ///tun
        ///pistol
        ///minge
        ///ochelari
        ///tren
        ///scrisoare
        ///zid
        ///radio
        ///pahar.
        /// </summary>
        internal static string text_cuvinte {
            get {
                return ResourceManager.GetString("text_cuvinte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memoreaza aceasta lista de obiecte folosind sistemul Peg.                    .
        /// </summary>
        internal static string text_info_1 {
            get {
                return ResourceManager.GetString("text_info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bifeaza butonul &quot;Imagine&quot; in cazul in care nu iti amintesti imaginea corespunzatoare numarului..
        /// </summary>
        internal static string text_info_2 {
            get {
                return ResourceManager.GetString("text_info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un sistem peg este o tehnica folositoare pentru memorarea unei liste de obiecte, nu foarte mare..
        /// </summary>
        internal static string text1_1 {
            get {
                return ResourceManager.GetString("text1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functioneaza prin asocierea obiectelor din lista pe care vrem sa o memoram, cu obiectele dintr-o alta lista bine cunoscuta.
        ///  O asemenea lista ar fi numerele de la 1 la 10, literele de la A la Z deoarece nu pot fi uitate. Problema cu aceste liste este ca 
        ///sunt abstracte (greu de visualizat), deaceea vom asocia fiecarui numar o imagine semnificativa..
        /// </summary>
        internal static string text1_2 {
            get {
                return ResourceManager.GetString("text1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceasta este o lista cu imaginile pe care le-am asociat noi fiecarui numar.
        ///  De retinut ! (Aceste imagini nu se vor modifica, ci numai informatiile atasate lor).
        ///  Totusi, daca doriti o alta imagine mai semnificativa, aveti libertatea de a schimba, dar de la bun inceput..
        /// </summary>
        internal static string text1_3 {
            get {
                return ResourceManager.GetString("text1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemplu :.
        /// </summary>
        internal static string text1_4 {
            get {
                return ResourceManager.GetString("text1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string text1_5 {
            get {
                return ResourceManager.GetString("text1_5", resourceCulture);
            }
        }
    }
}
