//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoTricks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texte1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texte1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemoTricks.Texte1", typeof(Texte1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memoreaza aceasta lista de obiecte folosind sistemul Peg.                    .
        /// </summary>
        internal static string text_info_1 {
            get {
                return ResourceManager.GetString("text_info_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bifeaza butonul &quot;Imagine&quot; in cazul in care nu iti amintesti imaginea corespunzatoare numarului..
        /// </summary>
        internal static string text_info_2 {
            get {
                return ResourceManager.GetString("text_info_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daca trebuie sa inveti liste de obiecte pentru scoala, servici, hobby sau alte scopuri, atunci sistemul Peg este exact ce ai nevoie.
        ///    Acest sistem este ideal atunci cand ai nevoie sa iti reamintesti obiectele intr-o anumita ordine..
        /// </summary>
        internal static string text1_1 {
            get {
                return ResourceManager.GetString("text1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functioneaza prin asocierea informatiilor pe care le cunosti , cum ar fi numerele de la 1 la 20, literele de la A la Z cu noile lucruri pe care vrei sa ti le amintesti.
        ///    Un “peg” (cuier) este un carlig mintal in care agatam informatia de care avem nevoie.
        ///Nu vei uita sa numeri pana la 20, si nici alfabetul. Totusi problema cu atasarea informatiilor de numere si litere este ca numerele si literele sunt abstracte (greu de vizualizat)..
        /// </summary>
        internal static string text1_2 {
            get {
                return ResourceManager.GetString("text1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemul Peg rezolva aceasta problema prin concretizarea literelor si a numerelor.
        ///Pentru aceasta, se ataseaza fiecarui numar o imagine a uni obiect cu care rimeaza sau are forma asemanatoare :.
        /// </summary>
        internal static string text1_3 {
            get {
                return ResourceManager.GetString("text1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceasta este list ape care o oferim noi, ea poate fi schimbata sau pot fi inlocuite unele obiecte cu altele care au o semnificatie speciala pentru tine..
        /// </summary>
        internal static string text1_4 {
            get {
                return ResourceManager.GetString("text1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string text1_5 {
            get {
                return ResourceManager.GetString("text1_5", resourceCulture);
            }
        }
    }
}
